### ISSUE TITLE
Inherit from DKPro Parent POM

### ISSUE THREAD

**Issue by reckart** [inception-project/external-recommender-dkpro-tc#9]
The DKPro Parent POM already sets up many things (compiler level, encoding, Maven plugins, code coverage profiles, etc etc). We could save a ton of settings by inheriting from it.

**Comment by reckart** [comment]
It also adds the "jacoco" profile which would fix the problem that the coverage reported by Jenkins to GitHub is always zero.

**Comment by Horsmann** [comment]
ah ok :) sorry
